### ISSUE TITLE
yaml parser: output parameter should not require type

### ISSUE THREAD

**Issue by hnicke** [eclipse/winery#201]
## Specification
According to TOSCA yaml spec 1.1 cos01:
>3.5.12 Parameter definition
A parameter definition is essentially a TOSCA property definition; however, it also allows a value to be assigned to it (as for a TOSCA property assignment). _In_ addition, in the case of output parameters, it can optionally inherit the data type of the value assigned to it rather than have an explicit data type defined for it.

## Non-Conformance 
When parsing an output which does not explicitly provide a type, the parser throws an exception:
`org.eclipse.winery.yaml.common.exception.MultiException: server_address:type is null!
Context::INLINE = topology_template:outputs:server_address
null
src/test/resources/builder/3_8_2_4_2-output_definition-1_1.yml`

This is the example used to provoke above failure, taken from the tosca spec(3_8_2_4_2-output_definition-1_1.yml):
```
tosca_definitions_version: tosca_simple_yaml_1_1

topology_template:
  outputs:
    server_address:
      description: The first private IP address for the provisioned server.
      value: { get_attribute: [ HOST, networks, private, addresses, 0 ] }
```
If a 'type' entry is added, the parser does not complain.
## How to solve
I wanted to fix it myself, but I realized due to the nature of the visitor pattern and how outputs are handled, it's not an easy fix.
Outputs are internally handled as `TParameterDefinition`.
`TTopologyTemplateDefinition.getOutputs()` may possibly return a new Type `TOutputDefinition` which is handled differently in `TypeValidator` than the `TParameterDefinition`.

@kleinech
