### ISSUE TITLE
yaml parser: Node templates with missing type field should be invalid

### ISSUE THREAD

**Issue by hnicke** [eclipse/winery#207]
When parsing a node template with missing `type` field, parser does not detect it as invalid node template.

According to TOSCA Spec1.1 cos01 ch. 3.7.3.1 (p. 103), a Node Template definition must always contain a `type` field.

#### Minimal template for reproducing the bug (missing_type.yaml):
```yaml
tosca_definitions_version: tosca_simple_yaml_1_1

description: a template containing a node template with missing type information

topology_template:
  node_templates:
    node_with_missing_type:
      properties:
        component_version: 3.5.1
```

#### Expected Behaviour:
e.g.: `Throw Exception: No type specified for node template  'node_with_missing_type'`

#### Witnessed Behaviour:
Passes without error.

@kleinech
