### ISSUE TITLE
Latest Docker image does not start (on Mac M1)

### ISSUE THREAD

**Issue by miwurster** [eclipse/winery#629]
I get the following error when starting the latest Docker image:
![image](https://user-images.githubusercontent.com/2610997/135849881-86512f96-8173-4771-8de3-77050da4a0b7.png)

I'm using the folloiwng Docker Compose config:
```yaml
  winery:
    image: opentosca/winery
    ports:
      - "8088:8080"
    environment:
      WINERY_TENANT_MODE: "true"
      WINERY_FEATURE_UPDATE_TEMPLATES: "true"
```

Can someone from you guys please confirm if this is an issue or whether the image starts as usual on Win/Unix?
